name: CI/CD Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
          -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

    - name: Build & Push Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USER }}/devops-basic:latest .
        docker push ${{ secrets.DOCKERHUB_USER }}/devops-basic:latest

    - name: Deploy to Server
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          docker pull ${{ secrets.DOCKERHUB_USER }}/devops-basic:latest &&
          cd ~/basic-devops &&
          docker compose up -d
        "

